RSpec.shared_context "Turkish Nouns" do
  let(:adam) { TurkishNoun.new("adam") }
  let(:ağaç) { TurkishNoun.new("ağaç") }
  let(:renk) { TurkishNoun.new("renk") }
  let(:araba) { TurkishNoun.new("araba") }
  let(:banyo) { TurkishNoun.new("banyo") }
  let(:köpek) { TurkishNoun.new("köpek") }
  let(:kapı) { TurkishNoun.new("kapı") }
  let(:top) { TurkishNoun.new("top") }
  let(:soru) { TurkishNoun.new("soru") }
  let(:kalem) { TurkishNoun.new("kalem") }
  let(:cami) { TurkishNoun.new("cami") }
  let(:göz) { TurkishNoun.new("göz") }
  let(:türk) { TurkishNoun.new("türk") }
  let(:ofis) { TurkishNoun.new("ofis") }
  let(:ev) { TurkishNoun.new("ev") }
  let(:park) { TurkishNoun.new("park") }
  let(:okul) { TurkishNoun.new("okul") }
end
